function [ phaseSpace ] = makeGaussBeam(mu_x, sigma_x,...
                                        mu_y, sigma_y,...
                                        mu_xp, sigma_xp,...
                                        mu_yp, sigma_yp,...
                                        sigma_s, T0, sigma_W0, N )
%This function outputs the 6D phase space
    
    %x - gaussian, described by mu_x and sigma_x, in m
    %y - gaussian, described by mu_y and sigma_y, in m
    %s - gaussian, described by sigma_s, s = z - z_synchronous
    %xp - gaussian, described by mu_xp and sigma_xp, in radians
    %yp - gaussian, described by mu_yp and sigma_yp, in radians
    %delta - gaussian - described by mu_T0, sigma_deltaW
    
    %x, y, xp, yp have no subtleties. T0 is the beam KINETIC energy in eV at
    %injection. sigma_W0 is the energy spread of the beam
    
    W0 = 511e3 + T0;
    W = normrnd(W0,sigma_W0,[1 N]);
    
    phaseSpace = [  normrnd(mu_x,sigma_x,[1 N]);...
                    normrnd(mu_y,sigma_y,[1 N]);...
                    normrnd(0,sigma_s,[1 N]);...
                    normrnd(mu_xp,sigma_xp,[1 N]);...
                    normrnd(mu_yp,sigma_yp,[1 N]);...
                    W/W0-1;...
                  ];
    
    
end

